apiVersion: apps/v1
kind: Deployment
metadata: 
    name: hello-nginx
    labels:
        app: hello-nginx
spec:
    replicas: 3
    selector:
        matchLabels:
            app: hello-nginx
    template:
        metadata: 
            labels: 
                app: hello-nginx
        spec:
            containers:
            - name: nginx
              image: nginx:1.17-alpine
              ports:
              - containerPort: 80

              volumeMounts:
              - mountPath: /etc/nginx/conf.d
                readOnly: true
                name: nginx-conf

            volumes:
            - name: nginx-conf
              configMap: 
                name: nginx-conf
                items:
                    - key: nginx.conf
                      path: nginx.conf
